const GET_USER_DEFAULT = 'GET_USER_DEFAULT';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const REGISTER = 'REGISTER';
const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
const UPDATE_PWD = 'UPDATE_PWD';

const TOGGLE_SHOW = 'TOGGLE_SHOW';
const INCREASE_COUNT = 'INCREASE_COUNT';

const actionTypes =  {
    GET_USER_DEFAULT,
    LOGIN,
    LOGOUT,
    REGISTER,
    UPDATE_USER_INFO,
    UPDATE_PWD,

    TOGGLE_SHOW,
    INCREASE_COUNT,
};

export default actionTypes;